<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerY7evbcu\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerY7evbcu/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerY7evbcu.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerY7evbcu\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerY7evbcu\appProdProjectContainer(array(
    'container.build_hash' => 'Y7evbcu',
    'container.build_id' => '9480fdf4',
    'container.build_time' => 1544537053,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerY7evbcu');
